package com.netapp.pbt.shared;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Data_Collection.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DataCollection implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** SET_ID. */
	private Long id;

	/** SET_NAME. */
	private String name;

	/** Data_Collection_Steps. */
	private String steps;

	/** Product. */
	private Product product;

	/** The set of Module_Data_Collection. */
	private Set<ModuleDataCollection> moduleDataCollectionSet;

	/**
	 * Constructor.
	 */
	public DataCollection() {
		this.moduleDataCollectionSet = new HashSet<ModuleDataCollection>();
	}

	/**
	 * Set the SET_ID.
	 * 
	 * @param id
	 *            SET_ID
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the SET_ID.
	 * 
	 * @return SET_ID
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the SET_NAME.
	 * 
	 * @param name
	 *            SET_NAME
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the SET_NAME.
	 * 
	 * @return SET_NAME
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the Data_Collection_Steps.
	 * 
	 * @param steps
	 *            Data_Collection_Steps
	 */
	public void setSteps(String steps) {
		this.steps = steps;
	}

	/**
	 * Get the Data_Collection_Steps.
	 * 
	 * @return Data_Collection_Steps
	 */
	public String getSteps() {
		return this.steps;
	}

	/**
	 * Set the Product.
	 * 
	 * @param product
	 *            Product
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * Get the Product.
	 * 
	 * @return Product
	 */
	public Product getProduct() {
		return this.product;
	}

	/**
	 * Set the set of the Module_Data_Collection.
	 * 
	 * @param moduleDataCollectionSet
	 *            The set of Module_Data_Collection
	 */
	public void setModuleDataCollectionSet(Set<ModuleDataCollection> moduleDataCollectionSet) {
		this.moduleDataCollectionSet = moduleDataCollectionSet;
	}

	/**
	 * Add the Module_Data_Collection.
	 * 
	 * @param moduleDataCollection
	 *            Module_Data_Collection
	 */
	public void addModuleDataCollection(ModuleDataCollection moduleDataCollection) {
		this.moduleDataCollectionSet.add(moduleDataCollection);
	}

	/**
	 * Get the set of the Module_Data_Collection.
	 * 
	 * @return The set of Module_Data_Collection
	 */
	public Set<ModuleDataCollection> getModuleDataCollectionSet() {
		return this.moduleDataCollectionSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DataCollection other = (DataCollection) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
