package com.netapp.pbt.shared;

import java.io.Serializable;

/**
 * Model class of Module_Data_Collection.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ModuleDataCollection implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Module. */
	private Module module;

	/** Data_Collection. */
	private DataCollection setDataCollection;

	/**
	 * Constructor.
	 */
	public ModuleDataCollection() {
	}

	/**
	 * Set the Module.
	 * 
	 * @param module
	 *            Module
	 */
	public void setModule(Module module) {
		this.module = module;
	}

	/**
	 * Get the Module.
	 * 
	 * @return Module
	 */
	public Module getModule() {
		return this.module;
	}

	/**
	 * Set the Data_Collection.
	 * 
	 * @param setDataCollection
	 *            Data_Collection
	 */
	public void setSetDataCollection(DataCollection setDataCollection) {
		this.setDataCollection = setDataCollection;
	}

	/**
	 * Get the Data_Collection.
	 * 
	 * @return Data_Collection
	 */
	public DataCollection getSetDataCollection() {
		return this.setDataCollection;
	}


}
