package com.netapp.pbt.shared;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Module.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Module implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Module_ID. */
	private Long id;

	/** Module_Name. */
	private String name;

	/** Module_Description. */
	private String description;

	/** DOT_Support. */
	private String dotSupport;

	/** Version. */
	private Version version;

	/** The set of Module_Data_Collection. */
	private Set<ModuleDataCollection> moduleDataCollectionSet;

	/** The set of Problems. */
	private Set<Problems> problemsSet;

	/** The set of Sub_Module. */
	private Set<SubModule> subModuleSet;

	/**
	 * Constructor.
	 */
	public Module() {
		this.moduleDataCollectionSet = new HashSet<ModuleDataCollection>();
		this.problemsSet = new HashSet<Problems>();
		this.subModuleSet = new HashSet<SubModule>();
	}

	/**
	 * Set the Module_ID.
	 * 
	 * @param id
	 *            Module_ID
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the Module_ID.
	 * 
	 * @return Module_ID
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the Module_Name.
	 * 
	 * @param name
	 *            Module_Name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the Module_Name.
	 * 
	 * @return Module_Name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the Module_Description.
	 * 
	 * @param description
	 *            Module_Description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the Module_Description.
	 * 
	 * @return Module_Description
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the DOT_Support.
	 * 
	 * @param dotSupport
	 *            DOT_Support
	 */
	public void setDotSupport(String dotSupport) {
		this.dotSupport = dotSupport;
	}

	/**
	 * Get the DOT_Support.
	 * 
	 * @return DOT_Support
	 */
	public String getDotSupport() {
		return this.dotSupport;
	}

	/**
	 * Set the Version.
	 * 
	 * @param version
	 *            Version
	 */
	public void setVersion(Version version) {
		this.version = version;
	}

	/**
	 * Get the Version.
	 * 
	 * @return Version
	 */
	public Version getVersion() {
		return this.version;
	}

	/**
	 * Set the set of the Module_Data_Collection.
	 * 
	 * @param moduleDataCollectionSet
	 *            The set of Module_Data_Collection
	 */
	public void setModuleDataCollectionSet(Set<ModuleDataCollection> moduleDataCollectionSet) {
		this.moduleDataCollectionSet = moduleDataCollectionSet;
	}

	/**
	 * Add the Module_Data_Collection.
	 * 
	 * @param moduleDataCollection
	 *            Module_Data_Collection
	 */
	public void addModuleDataCollection(ModuleDataCollection moduleDataCollection) {
		this.moduleDataCollectionSet.add(moduleDataCollection);
	}

	/**
	 * Get the set of the Module_Data_Collection.
	 * 
	 * @return The set of Module_Data_Collection
	 */
	public Set<ModuleDataCollection> getModuleDataCollectionSet() {
		return this.moduleDataCollectionSet;
	}

	/**
	 * Set the set of the Problems.
	 * 
	 * @param problemsSet
	 *            The set of Problems
	 */
	public void setProblemsSet(Set<Problems> problemsSet) {
		this.problemsSet = problemsSet;
	}

	/**
	 * Add the Problems.
	 * 
	 * @param problems
	 *            Problems
	 */
	public void addProblems(Problems problems) {
		this.problemsSet.add(problems);
	}

	/**
	 * Get the set of the Problems.
	 * 
	 * @return The set of Problems
	 */
	public Set<Problems> getProblemsSet() {
		return this.problemsSet;
	}

	/**
	 * Set the set of the Sub_Module.
	 * 
	 * @param subModuleSet
	 *            The set of Sub_Module
	 */
	public void setSubModuleSet(Set<SubModule> subModuleSet) {
		this.subModuleSet = subModuleSet;
	}

	/**
	 * Add the Sub_Module.
	 * 
	 * @param subModule
	 *            Sub_Module
	 */
	public void addSubModule(SubModule subModule) {
		this.subModuleSet.add(subModule);
	}

	/**
	 * Get the set of the Sub_Module.
	 * 
	 * @return The set of Sub_Module
	 */
	public Set<SubModule> getSubModuleSet() {
		return this.subModuleSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Module other = (Module) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
