package com.netapp.pbt.shared;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of Problem_Comments.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProblemComments implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long id;

	/** Comments. */
	private String comments;

	/** Submitter. */
	private String submitter;

	/** State. */
	private String state;

	/** Problems. */
	private Problems problemProblems;

	/** Date_of_submission. */
	private Date dateOfSubmission;

	/**
	 * Constructor.
	 */
	public ProblemComments() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the Comments.
	 * 
	 * @param comments
	 *            Comments
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * Get the Comments.
	 * 
	 * @return Comments
	 */
	public String getComments() {
		return this.comments;
	}

	/**
	 * Set the Submitter.
	 * 
	 * @param submitter
	 *            Submitter
	 */
	public void setSubmitter(String submitter) {
		this.submitter = submitter;
	}

	/**
	 * Get the Submitter.
	 * 
	 * @return Submitter
	 */
	public String getSubmitter() {
		return this.submitter;
	}

	/**
	 * Set the State.
	 * 
	 * @param state
	 *            State
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * Get the State.
	 * 
	 * @return State
	 */
	public String getState() {
		return this.state;
	}

	/**
	 * Set the Problems.
	 * 
	 * @param problemProblems
	 *            Problems
	 */
	public void setProblemProblems(Problems problemProblems) {
		this.problemProblems = problemProblems;
	}

	/**
	 * Get the Problems.
	 * 
	 * @return Problems
	 */
	public Problems getProblemProblems() {
		return this.problemProblems;
	}

	/**
	 * Set the Date_of_submission.
	 * 
	 * @param dateOfSubmission
	 *            Date_of_submission
	 */
	public void setDateOfSubmission(Date dateOfSubmission) {
		this.dateOfSubmission = dateOfSubmission;
	}

	/**
	 * Get the Date_of_submission.
	 * 
	 * @return Date_of_submission
	 */
	public Date getDateOfSubmission() {
		return this.dateOfSubmission;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProblemComments other = (ProblemComments) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
