package com.netapp.pbt.shared;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Problems.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
//@Entity
//@Table(name="Problems")
public class Problems implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Problem_ID. */
	private Long id;

	/** TITLE. */
	private String title;

	/** Log_Message. */
	private String logMessage;

	/** Troubleshooting_Steps. */
	private String troubleshootingSteps;

	/** Additional_Data_Collection. */
	private String additionalDataCollection;

	/** Burt_Numbers. */
	private String burtNumbers;

	/** Case_Numbers. */
	private String caseNumbers;

	/** submitter. */
	private String submitter;

	/** Environment_Details. */
	private String environmentDetails;

	/** DOT_Details. */
	private String dotDetails;

	/** Rating. */
	private Long rating;

	/** Module. */
	private Module module;

	/** Sub_Module. */
	private SubModule subModule;

	/** Product. */
	private Product product;

	/** The set of Performance_Problems. */
	private Set<PerformanceProblems> performanceProblemsSet;

	/** The set of Problem_Comments. */
	private Set<ProblemComments> problemCommentsSet;

	/**
	 * Constructor.
	 */
	public Problems() {
		this.performanceProblemsSet = new HashSet<PerformanceProblems>();
		this.problemCommentsSet = new HashSet<ProblemComments>();
	}

	/**
	 * Set the Problem_ID.
	 * 
	 * @param id
	 *            Problem_ID
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the Problem_ID.
	 * 
	 * @return Problem_ID
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the TITLE.
	 * 
	 * @param title
	 *            TITLE
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Get the TITLE.
	 * 
	 * @return TITLE
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * Set the Log_Message.
	 * 
	 * @param logMessage
	 *            Log_Message
	 */
	public void setLogMessage(String logMessage) {
		this.logMessage = logMessage;
	}

	/**
	 * Get the Log_Message.
	 * 
	 * @return Log_Message
	 */
	public String getLogMessage() {
		return this.logMessage;
	}

	/**
	 * Set the Troubleshooting_Steps.
	 * 
	 * @param troubleshootingSteps
	 *            Troubleshooting_Steps
	 */
	public void setTroubleshootingSteps(String troubleshootingSteps) {
		this.troubleshootingSteps = troubleshootingSteps;
	}

	/**
	 * Get the Troubleshooting_Steps.
	 * 
	 * @return Troubleshooting_Steps
	 */
	public String getTroubleshootingSteps() {
		return this.troubleshootingSteps;
	}

	/**
	 * Set the Additional_Data_Collection.
	 * 
	 * @param additionalDataCollection
	 *            Additional_Data_Collection
	 */
	public void setAdditionalDataCollection(String additionalDataCollection) {
		this.additionalDataCollection = additionalDataCollection;
	}

	/**
	 * Get the Additional_Data_Collection.
	 * 
	 * @return Additional_Data_Collection
	 */
	public String getAdditionalDataCollection() {
		return this.additionalDataCollection;
	}

	/**
	 * Set the Burt_Numbers.
	 * 
	 * @param burtNumbers
	 *            Burt_Numbers
	 */
	public void setBurtNumbers(String burtNumbers) {
		this.burtNumbers = burtNumbers;
	}

	/**
	 * Get the Burt_Numbers.
	 * 
	 * @return Burt_Numbers
	 */
	public String getBurtNumbers() {
		return this.burtNumbers;
	}

	/**
	 * Set the Case_Numbers.
	 * 
	 * @param caseNumbers
	 *            Case_Numbers
	 */
	public void setCaseNumbers(String caseNumbers) {
		this.caseNumbers = caseNumbers;
	}

	/**
	 * Get the Case_Numbers.
	 * 
	 * @return Case_Numbers
	 */
	public String getCaseNumbers() {
		return this.caseNumbers;
	}

	/**
	 * Set the submitter.
	 * 
	 * @param submitter
	 *            submitter
	 */
	public void setSubmitter(String submitter) {
		this.submitter = submitter;
	}

	/**
	 * Get the submitter.
	 * 
	 * @return submitter
	 */
	public String getSubmitter() {
		return this.submitter;
	}

	/**
	 * Set the Environment_Details.
	 * 
	 * @param environmentDetails
	 *            Environment_Details
	 */
	public void setEnvironmentDetails(String environmentDetails) {
		this.environmentDetails = environmentDetails;
	}

	/**
	 * Get the Environment_Details.
	 * 
	 * @return Environment_Details
	 */
	public String getEnvironmentDetails() {
		return this.environmentDetails;
	}

	/**
	 * Set the DOT_Details.
	 * 
	 * @param dotDetails
	 *            DOT_Details
	 */
	public void setDotDetails(String dotDetails) {
		this.dotDetails = dotDetails;
	}

	/**
	 * Get the DOT_Details.
	 * 
	 * @return DOT_Details
	 */
	public String getDotDetails() {
		return this.dotDetails;
	}

	/**
	 * Set the Rating.
	 * 
	 * @param rating
	 *            Rating
	 */
	public void setRating(Long rating) {
		this.rating = rating;
	}

	/**
	 * Get the Rating.
	 * 
	 * @return Rating
	 */
	public Long getRating() {
		return this.rating;
	}

	/**
	 * Set the Module.
	 * 
	 * @param module
	 *            Module
	 */
	public void setModule(Module module) {
		this.module = module;
	}

	/**
	 * Get the Module.
	 * 
	 * @return Module
	 */
	public Module getModule() {
		return this.module;
	}

	/**
	 * Set the Sub_Module.
	 * 
	 * @param subModule
	 *            Sub_Module
	 */
	public void setSubModule(SubModule subModule) {
		this.subModule = subModule;
	}

	/**
	 * Get the Sub_Module.
	 * 
	 * @return Sub_Module
	 */
	public SubModule getSubModule() {
		return this.subModule;
	}

	/**
	 * Set the Product.
	 * 
	 * @param product
	 *            Product
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * Get the Product.
	 * 
	 * @return Product
	 */
	public Product getProduct() {
		return this.product;
	}

	/**
	 * Set the set of the Performance_Problems.
	 * 
	 * @param performanceProblemsSet
	 *            The set of Performance_Problems
	 */
	public void setPerformanceProblemsSet(Set<PerformanceProblems> performanceProblemsSet) {
		this.performanceProblemsSet = performanceProblemsSet;
	}

	/**
	 * Add the Performance_Problems.
	 * 
	 * @param performanceProblems
	 *            Performance_Problems
	 */
	public void addPerformanceProblems(PerformanceProblems performanceProblems) {
		this.performanceProblemsSet.add(performanceProblems);
	}

	/**
	 * Get the set of the Performance_Problems.
	 * 
	 * @return The set of Performance_Problems
	 */
	public Set<PerformanceProblems> getPerformanceProblemsSet() {
		return this.performanceProblemsSet;
	}

	/**
	 * Set the set of the Problem_Comments.
	 * 
	 * @param problemCommentsSet
	 *            The set of Problem_Comments
	 */
	public void setProblemCommentsSet(Set<ProblemComments> problemCommentsSet) {
		this.problemCommentsSet = problemCommentsSet;
	}

	/**
	 * Add the Problem_Comments.
	 * 
	 * @param problemComments
	 *            Problem_Comments
	 */
	public void addProblemComments(ProblemComments problemComments) {
		this.problemCommentsSet.add(problemComments);
	}

	/**
	 * Get the set of the Problem_Comments.
	 * 
	 * @return The set of Problem_Comments
	 */
	public Set<ProblemComments> getProblemCommentsSet() {
		return this.problemCommentsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Problems other = (Problems) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
