package com.netapp.pbt.shared;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Sub_Module.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SubModule implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Sub_Module_ID. */
	private Long id;

	/** Sub_Module_Name. */
	private String name;

	/** Sub_Module_Description. */
	private String description;

	/** Module. */
	private Module module;

	/** The set of Problems. */
	private Set<Problems> problemsSet;

	/**
	 * Constructor.
	 */
	public SubModule() {
		this.problemsSet = new HashSet<Problems>();
	}

	/**
	 * Set the Sub_Module_ID.
	 * 
	 * @param id
	 *            Sub_Module_ID
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the Sub_Module_ID.
	 * 
	 * @return Sub_Module_ID
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the Sub_Module_Name.
	 * 
	 * @param name
	 *            Sub_Module_Name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the Sub_Module_Name.
	 * 
	 * @return Sub_Module_Name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the Sub_Module_Description.
	 * 
	 * @param description
	 *            Sub_Module_Description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the Sub_Module_Description.
	 * 
	 * @return Sub_Module_Description
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the Module.
	 * 
	 * @param module
	 *            Module
	 */
	public void setModule(Module module) {
		this.module = module;
	}

	/**
	 * Get the Module.
	 * 
	 * @return Module
	 */
	public Module getModule() {
		return this.module;
	}

	/**
	 * Set the set of the Problems.
	 * 
	 * @param problemsSet
	 *            The set of Problems
	 */
	public void setProblemsSet(Set<Problems> problemsSet) {
		this.problemsSet = problemsSet;
	}

	/**
	 * Add the Problems.
	 * 
	 * @param problems
	 *            Problems
	 */
	public void addProblems(Problems problems) {
		this.problemsSet.add(problems);
	}

	/**
	 * Get the set of the Problems.
	 * 
	 * @return The set of Problems
	 */
	public Set<Problems> getProblemsSet() {
		return this.problemsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SubModule other = (SubModule) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
