package com.netapp.pbt.shared;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Version.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Version implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long id;

	/** Version_Number. */
	private String number;

	/** Version_Name. */
	private String name;

	/** Version_Release_Date. */
	private Date releaseDate;

	/** Product. */
	private Product product;

	/** The set of Module. */
	private Set<Module> moduleSet;

	/**
	 * Constructor.
	 */
	public Version() {
		this.moduleSet = new HashSet<Module>();
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the Version_Number.
	 * 
	 * @param number
	 *            Version_Number
	 */
	public void setNumber(String number) {
		this.number = number;
	}

	/**
	 * Get the Version_Number.
	 * 
	 * @return Version_Number
	 */
	public String getNumber() {
		return this.number;
	}

	/**
	 * Set the Version_Name.
	 * 
	 * @param name
	 *            Version_Name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the Version_Name.
	 * 
	 * @return Version_Name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the Version_Release_Date.
	 * 
	 * @param releaseDate
	 *            Version_Release_Date
	 */
	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	/**
	 * Get the Version_Release_Date.
	 * 
	 * @return Version_Release_Date
	 */
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	/**
	 * Set the Product.
	 * 
	 * @param product
	 *            Product
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * Get the Product.
	 * 
	 * @return Product
	 */
	public Product getProduct() {
		return this.product;
	}

	/**
	 * Set the set of the Module.
	 * 
	 * @param moduleSet
	 *            The set of Module
	 */
	public void setModuleSet(Set<Module> moduleSet) {
		this.moduleSet = moduleSet;
	}

	/**
	 * Add the Module.
	 * 
	 * @param module
	 *            Module
	 */
	public void addModule(Module module) {
		this.moduleSet.add(module);
	}

	/**
	 * Get the set of the Module.
	 * 
	 * @return The set of Module
	 */
	public Set<Module> getModuleSet() {
		return this.moduleSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Version other = (Version) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
